owner: cebreus
repo: upptime

sites:
  - name: cebre.us
    url: 'https://www.cebre.us/'
    icon: 'https://www.cebre.us/favicon.ico'
  - name: tanecni-divadlo.cz
    url: 'https://www.tanecni-divadlo.cz'
    icon: 'https://scontent-prg1-1.xx.fbcdn.net/v/t1.18169-9/10329286_10152333624882870_4274816468418541583_n.png?_nc_cat=106&ccb=1-6&_nc_sid=09cbfe&_nc_ohc=nOcaOXvEHVoAX_s--0e&tn=v_q9sGbG8FnBwxyI&_nc_ht=scontent-prg1-1.xx&oh=00_AT8QD_3TSSC_2vgSrKgJFqcXpAOKt44D39PjvUAbaFoN3Q&oe=629A109B'
  - name: Sébastien Thomas Bagnoud
    url: 'https://www.sebastienbagnoud.eu/'
    icon: 'https://www.sebastienbagnoud.eu/favicon.ico'

status-website:
  cname: upptime.cebre.us
  logoUrl: 'https://lh3.googleusercontent.com/a-/AOh14Gh1FJXRWLCuwbyxVJWs4MZ-PxxKk76kGKWvyCA0vCI=s192-c-mo'
  name: Upptime
  favicon: 'https://www.cebre.us/assets/favicons/favicon-48x48.png'
  metaTags:
    - name: color-scheme
      content: dark light
    - name: robots
      content: noindex
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: 'https://github.com/$OWNER/$REPO'

i18n:
  footer: ''
