owner: cebreus
repo: upptime

sites:
  - name: cebre.us
    url: 'https://www.cebre.us/'
    icon: 'https://www.cebre.us/favicon.ico'
  - name: tanecni-divadlo.cz
    url: 'https://www.tanecni-divadlo.cz'

status-website:
  cname: upptime.cebre.us
  logoUrl: 'https://lh3.googleusercontent.com/a-/AOh14Gh1FJXRWLCuwbyxVJWs4MZ-PxxKk76kGKWvyCA0vCI=s192-c-mo'
  name: Upptime
  favicon: 'https://www.cebre.us/assets/favicons/favicon-48x48.png'
  metaTags:
    - name: color-scheme
      content: dark light
    - name: robots
      content: noindex
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: 'https://github.com/$OWNER/$REPO'

i18n:
  footer: ''
